name: CI

on:
  push:
    branches:
    - master
    - 'release/**'
  pull_request:
    branches:
    - master
    - 'release/**'

jobs:
  build-test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup Git
        run: |
          git config --global url."https://${{ secrets.ARTIFACT_BUILD_GITHUB_TS_DEVOPS_PAT }}@github.com/".insteadOf ssh://git@github.com/

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: yarn install
        run: yarn install --immutable
          
      - name: yarn test
        run: yarn test

      - name: Run codacy-coverage-reporter
        continue-on-error: true
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
